- dist/button/index.wxss
- dist/message/index.wxml
- examples/dist/button/index.wxss
- examples/dist/message/index.wxml
- examples/pages/basic/pages/button/index.wxml
- examples/pages/response/pages/message/index.js
- src/button/index.less
- src/message/index.wxml
> fix:更改message图标与文字隐藏不同步

- src/status-show/index.wxml
> fix:更改status-show按钮事件

- dist/price/index.js
- dist/price/index.json
- dist/price/index.wxml
- dist/price/index.wxss
- examples/app.json
- examples/dist/price/index.js
- examples/dist/price/index.json
- examples/dist/price/index.wxml
- examples/dist/price/index.wxss
- examples/pages/navigator/index/index.js
- examples/pages/navigator/index/index.json
- examples/pages/navigator/index/index.wxml
- examples/pages/navigator/index/index.wxss
- examples/pages/navigator/index/navi.js
- examples/pages/navigator/shopping/index.js
- examples/pages/navigator/shopping/index.json
- examples/pages/navigator/shopping/index.wxml
- examples/pages/navigator/shopping/index.wxss
- examples/pages/navigator/shopping/shop-navi.js
- examples/pages/shopping/pages/price/index.js
- examples/pages/shopping/pages/price/index.json
- examples/pages/shopping/pages/price/index.wxml
- examples/pages/shopping/pages/price/index.wxss
- examples/pages/shopping/pages/price/price-nav.js
- src/price/index.js
- src/price/index.json
- src/price/index.less
- src/price/index.wxml
> feat:新增price组件

- dist/custom-tab-bar/index.js
- examples/dist/custom-tab-bar/index.js
- examples/pages/components/nav/pages/tabbar/index.js
- examples/pages/navigator/filter/filter-navi.js
- src/custom-tab-bar/index.js
* fix: 修复自定义用法下不显示tabbar内容的bug
* fix: 修改过滤器ClassName的描述
* fix: 修改tabbar事件名=>lintap
> fix: 修复自定义用法下不显示tabbar内容的bug (#121)

- dist/input/index.js
- dist/input/index.wxml
- examples/dist/input/index.js
- examples/dist/input/index.wxml
- examples/pages/components/form/pages/rules/index.js
- src/input/index.js
- src/input/index.wxml
* fix: 修复自定义用法下不显示tabbar内容的bug
* fix: 修改过滤器ClassName的描述
* fix: 修改tabbar事件名=>lintap
* fix: 增加input的l-label-class 外部样式类
* fix:修复rules引入文件路径错误
> fix:修复自定义用法下不显示tabbar内容的bug (#124)

- dist/price/index.wxml
- examples/dist/price/index.wxml
- src/price/index.wxml
fix:修改price组件countColor属性不起作用问题
> fix:修改price组件countColor属性不起作用问题

- dist/behaviors/countdown.js
- src/behaviors/countdown.js
> feat：countdown组件增加正计时功能

- README.md
- dist/behaviors/countdown.js
- dist/search-bar/index.js
- examples/dist/behaviors/countdown.js
- examples/dist/search-bar/index.js
- examples/pages/components/view/pages/countdown/index.wxml
- package.json
- src/behaviors/countdown.js
- src/search-bar/index.js
- countdown组件增加正计时功能
- 修复search-bar组件缺少方法
>  feat:发布0.4.2版本

- README.md
- package.json
> feat:发布0.4.4版本

- README.md
- dist/segment/index.json
- examples/dist/segment/index.json
- package.json
- src/segment/index.json
>  feat:发布0.4.4版本

- dist/segment/index.wxml
- examples/dist/segment/index.wxml
- src/segment/index.wxml
> fix:修复segment组件外部样式类

- dist/avatar/index.js
- dist/list/index.js
- dist/textarea/index.js
- examples/dist/avatar/index.js
- examples/dist/list/index.js
- examples/dist/textarea/index.js
- src/avatar/index.js
- src/list/index.js
- src/textarea/index.js
将需要使用detail.detail获取信息的事件层级更改为detail一层
> fix:统一调整事件层级

- dist/radio-group/index.js
- examples/dist/radio-group/index.js
- src/radio-group/index.js
fix: 去掉radio组件初始化时对value值的合法校验
> fix: 去掉radio组件初始化时对value值的合法校验

- dist/checkbox-group/index.js
- examples/dist/checkbox-group/index.js
- src/checkbox-group/index.js
fix: 修复checkbox节点移除时校验key值报错的问题
> fix: 修复checkbox节点移除时校验key值报错的问题

- examples/pages/components/form/pages/checkbox/index.wxml
- examples/pages/components/form/pages/checkbox/index.wxss
> fix: 修改checkbox外部样式类的使用案例

- dist/checkbox-group/index.js
- dist/checkbox/index.js
- examples/dist/checkbox-group/index.js
- examples/dist/checkbox/index.js
- src/checkbox-group/index.js
- src/checkbox/index.js
fix:修复checkbox设置动态设置选项后 最小选中数无法正常实现的bug
> fix:修复checkbox最小选中数的bug(#601)

- dist/tag/index.js
- dist/tag/index.wxml
- examples/dist/tag/index.js
- examples/dist/tag/index.wxml
- src/tag/index.js
- src/tag/index.wxml
修复tag组件 设置 icon-name 不能正确显示图标的方式（#618）
> fix:修复tag组件 使用 icon 的方式（#618）

- dist/status-show/index.js
- examples/dist/status-show/index.js
- src/status-show/index.js
修复status-show组件custom不能正确使用的bug
> fix:修复status-show组件custom的使用方式（#619）

- dist/loading/index.wxml
- examples/dist/loading/index.wxml
- src/loading/index.wxml
增加loading组件非全屏模式下的外部样式l-container-class
> fix: 增加loading组件非全屏模式下的外部样式l-container-class(#640)

- dist/behaviors/rules.js
- dist/checkbox-group/index.js
- dist/form/index.js
- dist/input/index.js
- dist/radio-group/index.js
- dist/rate/index.js
- dist/textarea/index.js
- examples/dist/behaviors/rules.js
- examples/dist/checkbox-group/index.js
- examples/dist/form/index.js
- examples/dist/input/index.js
- examples/dist/radio-group/index.js
- examples/dist/rate/index.js
- examples/dist/textarea/index.js
- src/behaviors/rules.js
- src/checkbox-group/index.js
- src/form/index.js
- src/input/index.js
- src/radio-group/index.js
- src/rate/index.js
- src/textarea/index.js
> fix: 修改表单重构后eslint代码格式问题。

- examples/pages/components/form/pages/rules/index.js
- examples/pages/components/form/pages/rules/index.wxml
- examples/pages/components/form/pages/rules/index.wxss
> fix: 修改rules组件的example。(#699)

- examples/pages/components/form/pages/form/index.wxml
- examples/pages/components/form/pages/form/index.wxss
- examples/pages/components/form/pages/textarea/index.wxml
- examples/pages/navigator/content/config/form-navi.js
> fix: 修改 form 组件的案例代码

- dist/tabs/index.wxml
- examples/dist/tabs/index.wxml
- src/tabs/index.wxml
新增 slot，用于自定义 Tabs 的标签栏，slot name 为 item.key.tab，在未填写 tab
属性时生效
示例：
``` html
<l-tabs>
<view slot="1.tab">标签一</view>
<view slot="2.tab">标签一</view>
<view slot="3.tab">标签一</view>
<l-tabpanel key="1" slot="1">
<l-tabpanel key="2" slot="2">
<l-tabpanel key="3" slot="3">
</l-tabs>
```
close #763
> Tabs 组件新增标签栏 slot

- dist/utils/node-util.js
- examples/dist/utils/node-util.js
- src/utils/node-util.js
该工具类对微信 wxml 节点选择 api 进行封装，方便选择节点信息
> 新增 NodeUtil 工具类

- package.json
* **Collapse:** 修复内容区域动态添加内容后不显示的问题 ([#794](https://github.com/TaleLin/lin-ui/issues/794)) ([cb03200](https://github.com/TaleLin/lin-ui/commit/cb032004d1b712ae0d822f7f63b548d9c237526a))
* **StatusShow:** 修复status_show组件在非全屏下的显示问题 ([#787](https://github.com/TaleLin/lin-ui/issues/787)) ([00c0440](https://github.com/TaleLin/lin-ui/commit/00c04400c33eb2b85ad77efe8c13c6ee20a366c5))
* **Tag:** 修复禁用状态下仍能触发 lintap 事件的问题 ([#795](https://github.com/TaleLin/lin-ui/issues/795)) ([31e6a47](https://github.com/TaleLin/lin-ui/commit/31e6a47c1e2d3fb94bf5f1c0483db16e7b903ec4))
* **Textarea:** 修改 textarea 组件默认宽度，由固定700rpx 改为 默认100% ([#749](https://github.com/TaleLin/lin-ui/issues/749)) ([af3830d](https://github.com/TaleLin/lin-ui/commit/af3830d592f0b1e85d4d4e3a822dce5564ed7383))
* **IndexList:** 新增 …
> chore(package.json): 发布 0.8.0 版本

- src/popup/index.js
- src/popup/index.json
- src/popup/index.less
- src/popup/index.wxml
Popup 引入 Transition 后出现穿透、卡顿等问题，暂时去除
close #808
> 去除 Popup 组件中 Transition 组件的使用

- src/input/index.js
- src/input/index.less
- src/input/index.wxml
show-eye 属性控制输入框右侧显隐密码按钮的显示
close #531
> Input 组件新增 show-eye 属性

- src/input/index.js
- src/input/index.wxml
l-input-class 覆盖小程序原生 input 组件样式
如果需要修改输入框文字对齐方向（如右对齐），则需要使用该外部样式类
close #137
> Input 组件新增外部样式类 l-input-class

- examples/pages/components/view/pages/arc-popup/index.js
- examples/pages/components/view/pages/arc-popup/index.json
- examples/pages/components/view/pages/arc-popup/index.wxml
- examples/pages/components/view/pages/arc-popup/index.wxss
- examples/pages/components/view/pages/arc-popup/popup-nav.js
- src/arc-popup/index.js
- src/arc-popup/index.less
- src/arc-popup/index.wxml
>  新增 ArcPopup 组件高级用法

- src/input/index.less
875 号 pr 误提交了错误的 css 样式，该 commit 进行修复
> 修复 Input 组件 css 样式问题

- .huskyrc
- commitlint.config.js
- package.json
> 升级 Husky 版本

- src/water-flow/index.js
- src/water-flow/index.wxml
> 修复 WaterFlow 组件数据为[]时不刷新的问题

- src/index-list/index.js
- src/index-list/index.wxml
l-sidebar-item-class 覆盖 sidebar-item 样式
> IndexList 组件新增 l-sidebar-item-class 外部样式类

- src/list/index.less
- src/list/index.wxml
> 修复组件右侧箭头图标样式

- src/water-flow/index.js
> 修复 WaterFlow 组件 linitemtap 事件未返回自定义数据问题

- src/icon/index.js
- src/icon/index.wxml
删除 l-self-class、l-class-self 无用外部样式类
> 去除 Icon 组件无用外部样式类

- src/collapse/index.js
> 修复 Collapse 组件 expand-item-id 默认展开属性无效问题

- src/price/index.js
- src/price/index.wxml
l-dot-class 覆盖小数点样式
l-decimal-class 覆盖小数部分样式
close #943
> Price 组件新增 l-decimal-class 和 l-dot-class 外部样式类

- src/form/index.js
> 修复 Form 组件 linreset 事件无效的问题

- src/image-picker/index.wxml
- src/list/index.wxml
- src/segment/index.wxml
- src/tabs/index.wxml
将所有引用 Icon 并使用 l-self-class 外部样式类的组件 class 名称移至 l-class 外部样式类
> 修复 Icon 组件 l-self-class 外部样式类无效问题

- src/segment/index.js
可在 segment-item 组件上使用如下方式绑定数据：
```html
<l-segment-item data-cell="测试数据" />
```
该数据可在 `bind:linchange` 事件中获取
> Segment 组件新增 data-cell 数据绑定方式

- package.json
- src/popup/index.less
因使用了 less 的 each 函数，所以将 less 升级到 3.12.2 版本
close #978
> 修复 Popup 组件频繁切换 显示/隐藏 状态闪烁的问题

- src/button/index.less
> 修复 Button 组件 size 为 long 时，加载中图标没有右边距的问题

- commitlint.config.js
- src/album/index.wxml
- src/avatar/index.wxml
- src/badge/index.wxml
- src/button/index.wxml
- src/capsule-bar/index.wxml
- src/checkbox/index.wxml
- src/collapse-item/index.wxml
- src/combined-tabs/index.wxml
- src/counter/index.wxml
- src/custom-tab-bar/index.wxml
- src/form/index.wxml
- src/grid-item/index.wxml
- src/grid/index.wxml
- src/input/index.wxml
- src/list/index.wxml
- src/loadmore/index.wxml
- src/notice-bar/index.wxml
- src/radio/index.wxml
- src/rate/index.wxml
- src/search-bar/index.wxml
- src/segment/index.wxml
- src/slide-view/index.wxml
- src/status-show/index.wxml
- src/tabs/index.wxml
- src/tag/index.wxml
使用 `mut-bind:tap` 替换 `bind:tap`，解决 tap 冒泡导致 lintap 被触发两次的问题
> 修复组件内部 bind:tap 冒泡导致 lintap 被触发两次的问题

- examples/pages/components/layout/pages/album/index.wxml
- examples/pages/components/layout/pages/album/index.wxss
- src/album/index.js
- src/album/index.less
- src/album/index.wxml
- src/album/index.wxs
> Album 组件新增自定义图片显示数量及状态

- src/counter/index.js
- src/counter/index.wxml
> Counter 组件新增 lininput 事件

- src/segment/index.less
> 开启 Segment 组件惯性滚动以优化性能

- src/input/index.js
- src/input/index.wxml
l-row-class 覆盖 input 下方横线样式
close #1018
> Input 组件新增 l-row-class 外部样式类

- src/grid-item/index.js
- src/grid-item/index.less
- src/grid-item/index.wxml
- src/grid/index.less
- src/grid/index.wxml
扩大 grid-item 组件点击范围，将 hover 效果移入 grid-item 组件
> 修复 Grid 组件体验问题

- src/grid/index.less
> 修复 Grid 组件 l-grid-item 样式改动导致组件不能居中

- src/grid/index.wxml
修复 Grid 组件 lintap 事件以及 tapGridItem 事件不会触发问题
close #1059
> 修复 Grid 组件 lintap 事件不会触发问题

- src/tabs/index.js
- src/tabs/index.wxml
> Tabs 组件新增 l-tabpanel-class 外部样式类

- src/image-picker/index.js
> 修复 ImagePicker 组件 urls 属性更新以后，图片不显示

- src/input/index.wxml
> 修复组件切换显隐密码在 ios 下会清空问题

- src/image-picker/index.less
- src/image-picker/index.wxml
由于 GridItem 组件样式修改导致组件样式出错  
close #1085
> 修复 ImagePicker 组件样式问题

- src/index-list/index.js
> 修复 IndexList 组件点击 Sidebar 后滚动页面无法改变选中位置的问题

- src/album/index.wxml
close #1100
BREAKING CHANGE: 去除单张图片底部多余空隙
> 去除 Album 组件单张图片底部多余空隙

- src/button/index.js
- src/button/index.wxml
disabled-hover 属性用于禁用按钮 hover 效果
close #1112
> Button 组件新增 disabled-hover 属性

- src/step/index.wxml
- src/steps/index.js
- src/steps/index.less
- src/steps/index.wxml
由该 commit 造成：
https://github.com/TaleLin/lin-ui/commit/af34537a05ab188a8f07c1b1f81c7a898db1be11#diff-f3d2004a2adfde057bce8e22a9c6af3d21fdcffdb24e6c8b39a49c42973a7cc6
close #1111
> 修复历史 commit 造成的 Steps 组件 reverse 功能丢失

- src/image-clipper/index.js
- src/image-clipper/index.wxml
> 修复 ImageClipper 组件异常警告

- commitlint.config.js
- src/form-item/index.less
> Form 组件修复 label-placement 为 column 时未左对齐的问题

- src/image-clipper/calculate.js
- src/image-clipper/index.js
1. 修复 #1129
2. 优化拖动裁剪框时的计算
close #1129
> 修复 ImageClipper 组件拖动裁剪框时有几率报错问题

- src/segment/index.wxml
> 修复 Segment 组件 mut-bind 导致的添加徽标后大范围无法点击问题

- src/capsule-bar/index.js
- src/capsule-bar/index.wxml
> feat(CapsuleBar): 新增 hidden-title 属性

- src/capsule-bar/index.js
- src/capsule-bar/index.wxml
> feat(CapsuleBar): 新增标题栏 Slot

- src/image-clipper/index.wxml
> 修复 ImageClipper 组件 canvas 2d 导致的无法绘制图片问题

- build/index.js
- commitlint.config.js
> fix(DynamicBuild): 修复按需编译未复制 core 文件夹的问题

- src/rate/index.less
> fix(Rate): 修复星星图片尺寸过小时错位的问题

- examples/pages/components/form/pages/rate/index.wxml
- examples/pages/components/form/pages/rate/index.wxss
- examples/pages/components/nav/pages/tabs/index.wxml
- src/tabs/index.wxml
> fix(Tabs): 修复添加徽标后点击事件无法触发的问题

- examples/pages/components/form/pages/rate/index.wxml
- src/rate/index.js
- src/rate/index.less
- src/rate/index.wxml
> feat(Rate): 新增 item-gap 属性

- examples/pages/components/layout/pages/album/index.js
- src/album/index.js
1.修复在页面 JS 中设置传入 urls 无效的问题
2.删除无用的 row、column 属性
close #1172
> fix(Album): 修复在页面 JS 中设置传入 urls 无效的问题

- src/calendar/index.json
> 修复 Calendar 组件引入其他组件路径错误

- config/styles/_mixins.less
- src/calendar/calendar.wxml
- src/calendar/index.less
> 修复 Calendar 组件全面屏适配问题

- build/index.js
> fix(DynamicBuild): 修复按需编译时 common 下 js 文件缺失的问题

- src/message/index.js
- src/message/index.wxml
> fix(Message): 修复 l-image-class 外部样式类不生效的问题

- src/form/index.wxml
> feat(Form): 新增 submit-front、reset-front、reset-behind 插槽

- src/checkbox/index.wxml
> fix(Checkbox): 修复 slot 传入 lin-ui 组件点击无法修改状态的问题

- src/notice-bar/index.js
在使用 api 加载通告栏内容的场景使用：
修改通告栏内容后，使用 this.selecComponent() 选择组件实例
然后调用 flush() 方法刷新动画
close #1248
> feat(NoticeBar): 新增 flush 方法用于刷新动画

- src/image-picker/index.js
- src/image-picker/index.json
- src/image-picker/index.less
- src/image-picker/index.wxml
1.事件抛出 url 统一格式为 Array<String>
2.废弃 custom 属性
3.size-type 类型从 String 修改为 Array<String>
close #1292,#1275,#1183,#1147,#1262
> refactor(ImagePicker): 重构 ImagePicker 组件

- src/toast/index.js
1.新增 linShow 函数
2.新增 linHide 函数
> feat(Toast): 新增开放函数

- src/image-picker/index.js
1. 修复 value 为 null 导致的组件不显示的问题
2. 修复 maxImageSize 为 0 时导致无法添加图片的问题
> fix(ImagePicker): 修复多个报错问题

- examples/app.json
- examples/pages/navigator/content/config/animation-navi.js
> chore(app.json、animation-navi.js)
